---
main:
  params: [event]
  steps:
  - init:
      assign:
      - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - instances: ${event.instances}
      - retain_days: ${event.retainDays}
      - current_unix_time: ${sys.now()}
      - expiration_unix_time: ${current_unix_time - (retain_days * 86400)}
  - for_each_instances:
      for:
        value: instance
        in: ${instances}
        steps:          
        - backup:
            try:
              call: backup_sql_workflow
              args:
                project_id: ${project_id}
                instance: ${instance}
            except:
              as: e
              steps:
              - known_errors:
                  switch:
                  - condition: ${e.code == 404}
                    call: sys.log
                    args:
                      text: ${instance.name + " Not Found"}
                      severity: "ERROR"
                  - condition: true
                    call: sys.log
                    args:
                      json: ${e}
                      severity: "ERROR"
              - next_instance:
                  next: continue
        - expiration:
            call: expiration_backup_workflow
            args:
              project_id: ${project_id}
              instance: ${instance}
              expiration_unix_time: ${expiration_unix_time}
  - job_completed:
      return: "job completed"
      
backup_sql_workflow:
  params: [project_id,instance]
  steps:
  - init:
      assign:
        - sql_name: ${instance.name} 
        - location: ${instance.location}
  - create_sql_backup:
      call: googleapis.sqladmin.v1.backupRuns.insert
      args:
        instance: ${sql_name}
        project: ${project_id}
        body: 
          location: ${location}
      result: insertResult    
  - print_log:
      call: sys.log
      args:
        json: ${insertResult}
        severity: "NOTICE"

expiration_backup_workflow:
  params: [project_id,instance,expiration_unix_time]
  steps:
  - init:
      assign:
        - sql_name: ${instance.name}
  - get_expiration_backup:
      call: googleapis.sqladmin.v1.backupRuns.list
      args:
        instance: ${sql_name}
        project: ${project_id}
      result: listResult
  - for_each_backups:
      for:
        value: backup
        in: ${listResult.items}
        steps:
        - filter_backup:
            switch:
            - condition: ${backup.type == "ON_DEMAND" AND time.parse(backup.endTime) < expiration_unix_time}
              steps:
              - delete_backup:
                  call: googleapis.sqladmin.v1.backupRuns.delete
                  args:
                    id: ${backup.id}
                    instance: ${sql_name}
                    project: ${project_id}
                  result: deleteResult
              - print_log:  
                  call: sys.log
                  args:
                    json: ${deleteResult}
                    severity: "NOTICE"