apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: spring-petclinic
images:
  - name: spring-petclinic
    newName: spring-petclinic
    newTag: v1.0.00
replicas:
- name: spring-petclinic
  count: 3       
resources:
- deployment.yml
- service.yml
- ingress.yml