main:
  params: [event]
  steps:
  - init:
      assign:
      - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - message: ${json.decode(base64.decode(event.data.message.data))}
      - state: ${message.incident.state}
      - gce_name: ${message.incident.policy_user_labels.gce_name}
      - gce_zone: ${message.incident.policy_user_labels.gce_zone}
  - open:
      switch:
      - condition: ${state == "open"}
        steps:
        - reset_gce:
            call: googleapis.compute.v1.instances.reset
            args:
              instance: ${gce_name}
              project: ${project_id}
              zone: ${gce_zone}
            result: resetResult
        - print_result:
            return: ${resetResult}