---
steps:

  - name: gcr.io/cloud-builders/git
    entrypoint: git
    args: ["clone", "$_GIT_REPO"]
  
  - name: maven:3.8-openjdk-17
    dir: "$_DIR_NAME"
    entrypoint: mvn
    args: ["clean", "package", "-Dmaven.test.skip=true"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "Dockerfile", "-t", "$_REGISTRY_NAME/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_TAG_NAME", "--build-arg=JAR_FILE=target/*.jar", "$_DIR_NAME"]

images: ["$_REGISTRY_NAME/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_TAG_NAME"]


substitutions:
  _GIT_REPO: https://github.com/spring-projects/spring-petclinic
  _DIR_NAME: spring-petclinic
  _REGISTRY_NAME: us-central1-docker.pkg.dev
  _REPO_NAME: demo
  _IMAGE_NAME: spring-petclinic
  _TAG_NAME: v1.0.00

timeout: 6000s